Additional Tariff Cost Multiplier on Electricity Capacity[solar PV es] = 0.20
Additional Tariff Cost Multiplier on Electricity Capacity[onshore wind es] = 0.10
Additional Tariff Cost Multiplier on EV Batteries[LDVs,passenger,battery electric vehicle] = -0.097
Additional Tariff Cost Multiplier on EV Batteries[LDVs,passenger,plugin hybrid vehicle] = -0.063
Additional Tariff Cost Multiplier on Grid Batteries = -0.058
